version: '3'
services:
    cert-server:
        build: .
        container_name: cert-server
        hostname: cert-server
        restart: unless-stopped #  - if you want container to persistent through
        # host reboots.
        #
        # See Logging below. This sets a maximum of five log files with a max 
        # size of 10 Mb each. So at most 50 Mb of logs for that container. Tune
        # those numbers as you see fit.
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        ports:
          - target: 9000
            published: 9000
            mode: host # get real ip for NGINX access control, NOT SUPPORTED IN Docker for Desktop
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./default:/etc/nginx/conf.d/default.conf # for easier nginx config editing locally
        environment:
            DNS_CLOUDFLARE_CREDENTIALS: /run/secrets/cloudflare_credentials
        secrets: 
          - cloudflare_credentials
        command: ['sh', '-c', './create-cert.sh && nginx -g "daemon off;"']
secrets: 
  cloudflare_credentials: 
   file: cloudflare.ini 